name: Check Docker Image

on: 
  workflow_dispatch

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas
  IMAGE_LABEL: latest
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Image
        run: |
          # curl --silent -f --head -lL https://hub.docker.com/v2/repositories/${{ env.IMAGE_NAME }}/tags/${{ env.IMAGE_LABEL }}/ > /dev/null

          docker manifest inspect ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }}232 > /dev/null
          echo $?

          docker manifest inspect ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_LABEL }} > /dev/null
          echo $?

