name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas
  SSH_KEY_NAME: github
  DROPLET_NAME: jupyterlab-droplet
  DROPLET_SIZE: s-1vcpu-1gb
  DROPLET_REGION: LON1
  DROPLET_IMAGE: docker-20-04 

  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key and publish to DigitalOcean
        run: |
          ssh-keygen -N "" -f ~/digitalocean 

          export SSH_KEY_PUBLIC=$(cat ~/digitalocean.pub)
          export SSH_KEY=$(cat ~/digitalocean)
          export DO_SSH_KEY_ID=$(doctl compute ssh-key create github --verbose --public-key "$SSH_KEY_PUBLIC" --no-header --format ID)

          echo "::set-env name=DO_SSH_KEY_ID::$DO_SSH_KEY_ID"
          echo "::set-env name=SSH_KEY::$SSH_KEY"

      - name: Destroy JupyterLab Droplet
        run: |
          doctl compute droplet delete ${{ env.DROPLET_NAME }} --force || true

      - name: Create JupyterLab Droplet
        run: |
          export DO_PUBLIC_ID=$(doctl compute droplet create ${{ env.DROPLET_NAME }} --image ${{ env.DROPLET_IMAGE}} --region ${{ env.DROPLET_REGION }} --size ${{ env.DROPLET_SIZE }} --ssh-keys $DO_SSH_KEY_ID --wait --no-header --format PublicIPv4)

      - name: Destroy SSH Key
        run: |
          doctl compute ssh-key delete $DO_SSH_KEY_ID --force          

      - name: Deploy Docker to JupyterLab Droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: $DO_PUBLIC_ID # IP address of the server you wish to ssh into
          key: $SSH_KEY # Private or public key of the server
          username: root # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            echo 'Deployment successful to digital ocean' 