name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key
        run: |
          ssh-keygen -N "" -f digitalocean
          export PUBLIC_KEY=$(cat digitalocean.pub)
          echo $PUBLIC_KEY
          doctl compute ssh-key create github --verbose --public-key "$PUBLIC_KEY"  || true

      - name: Destroy Droplet
        run: |
          doctl compute droplet delete jupyterlab-droplet --force || true

      - name: Create a Docker Droplet
        run: |
          doctl compute droplet create jupyterlab-droplet --image docker-20-04 --region LON1 --size s-1vcpu-1gb --ssh-keys github --wait
          doctl compute droplet get jupyterlab-droplet --template "droplet IP: {{ .PublicIPv4}}                 

