name: Deploy to Heroku

on: 
  workflow_dispatch

env:
  HEROKU_EMAIL: dvillaj@gmail.com
  HEROKU_APP_NAME: jupyterlab-pandas
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

     - name: Update JUPYTERLAB_TOKEN on Heroku
        run: heroku config:set JUPYTERLAB_TOKEN=${{ secrets.JUPYTERLAB_TOKEN }} -a ${{ env.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}        

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ env.HEROKU_EMAIL }}
          
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
         