name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas
  SSH_KEY_NAME: github
  DROPLET_NAME: jupyterlab-droplet
  DROPLET_SIZE: s-1vcpu-1gb
  DROPLET_REGION: LON1
  DROPLET_IMAGE: docker-20-04 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key
        run: |
          ssh-keygen -N "" -f digitalocean
          export PUBLIC_KEY=$(cat digitalocean.pub)
          doctl compute ssh-key create ${{ env.SSH_KEY_NAME }} --verbose --public-key "$PUBLIC_KEY"  || true

      - name: Destroy Droplet
        run: |
          doctl compute droplet delete ${{ env.DROPLET_NAME }} --force || true

      - name: Create a Docker Droplet
        run: |
          DO_SSH_IDS=$(doctl compute ssh-key list --no-header --format ID)
          echo $DO_SSH_IDS
          doctl compute droplet create ${{ env.DROPLET_NAME }} --image ${{ env.DROPLET_IMAGE}} --region ${{ env.DROPLET_REGION }} --size ${{ env.DROPLET_SIZE }} --ssh-keys $DO_SSH_IDS --wait
          doctl compute droplet get ${{ env.DROPLET_NAME }} --template "droplet IP: {{ .PublicIPv4}}                 

