name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas
  SSH_KEY_NAME: github
  DROPLET_NAME: jupyterlab-droplet
  DROPLET_SIZE: s-1vcpu-1gb
  DROPLET_REGION: LON1
  DROPLET_IMAGE: docker-20-04 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key and publish to DigitalOcean
        id: create_ssh_id
        run: |
          ssh-keygen -N "" -f ~/digitalocean 

          SSH_KEY_PUBLIC=$(cat ~/digitalocean.pub)
          DO_SSH_KEY_ID=$(doctl compute ssh-key create github --verbose --public-key "$SSH_KEY_PUBLIC" --no-header --format ID)
          
          echo ::set-output name=key_id::$DO_SSH_KEY_ID

      - name: Destroy JupyterLab Droplet
        run: |
          doctl compute droplet delete ${{ env.DROPLET_NAME }} --force || true

      - name: Create JupyterLab Droplet
        id: create_droplet
        run: |
          DO_PUBLIC_IP=$(doctl compute droplet create ${{ env.DROPLET_NAME }} \
                --image ${{ env.DROPLET_IMAGE}} \
                --region ${{ env.DROPLET_REGION }} \
                --size ${{ env.DROPLET_SIZE }} \
                --ssh-keys ${{ steps.create_ssh_id.outputs.key_id }} \
                --wait \
                --no-header \
                --format PublicIPv4)

          echo ::set-output name=public_ip::$DO_PUBLIC_IP

      - name: Destroy SSH Key
        run: |
          doctl compute ssh-key delete ${{ steps.create_ssh_id.outputs.key_id }} --force          

      # - name: Deploy Docker to JupyterLab Droplet
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: ${{ steps.create_droplet.outputs.public_ip }}
      #     key: ${{ steps.create_ssh_id.outputs.ssh_key }}
      #     username: root
     
      #     script: |
      #       mkdir test 
      #       cd test 
      #       echo 'Deployment successful to digital ocean' 

      - name: Sleeping ...
        run: |
          sleep 30
          cat ~/digitalocean

      - name: check 22 port
        run: nc -zvw10 ${{ steps.create_droplet.outputs.public_ip }} 22 

      - name: Deploy Docker to JupyterLab Droplet
        run: |
          ssh -vvv -i ~/digitalocean -o "StrictHostKeyChecking no" root@${{ steps.create_droplet.outputs.public_ip }} bash <<EOF
          whoami
          EOF