name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create a Docker Droplet
        run: |
          doctl compute ssh-key create github --public-key "${{ secrets.DIGITALOCEAN_SSH_KEY_PUBLIC }}"
          # doctl compute droplet create jupyterlab-droplet --image docker-20-04 --region asm3 --size s-1vcpu-1gb --wait

