name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas
  SSH_KEY_NAME: github
  DROPLET_NAME: jupyterlab-droplet
  DROPLET_SIZE: s-1vcpu-1gb
  DROPLET_REGION: LON1
  DROPLET_IMAGE: docker-20-04 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create SSH key
        run: |
          ssh-keygen -N "" -f ~/.ssh/id_rsa 

      - name: Destroy JupyterLab Droplet
        run: |
          doctl compute droplet delete ${{ env.DROPLET_NAME }} --force || true

      - name: Create a Docker Droplet
        run: |
          export SSH_KEY_PUBLIC=$(cat ~/.ssh/id_rsa.pub)
          export DO_SSH_KEY=$(doctl compute ssh-key create github --verbose --public-key "$SSH_KEY_PUBLIC" --no-header --format ID)
          export DO_PUBLIC_ID=$(doctl compute droplet create ${{ env.DROPLET_NAME }} --image ${{ env.DROPLET_IMAGE}} --region ${{ env.DROPLET_REGION }} --size ${{ env.DROPLET_SIZE }} --ssh-keys $DO_SSH_KEY --wait --no-header --format PublicIPv4)
          doctl compute ssh-key delete $DO_SSH_KEY

          echo "PUBLIC ID = $DO_PUBLIC_ID"