name: Deploy to DigitalOcean

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'JypyterLab TOKEN'     
        required: true

env:
  DOCKERHUB_USER: dvillaj
  IMAGE_NAME: jupyterlab-pandas

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create a Docker Droplet
        run: doctl compute droplet create test --image ubuntu-18-04-x64 --region nyc3 --size s-1vcpu-1gb

