name: Destroy to DigitalOcean Infrastructure

on: 
  workflow_dispatch

env:
  DROPLET_TAG: jupyterlab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Check JupyterLab Droplet
        id: check_droplet
        run: |
          DO_ID=$(doctl compute droplet list \
                --tag-name ${{ env.DROPLET_TAG }}  \
                --no-header \
                --format ID)

          if [ -z "$DO_ID" ]
          then
              echo "JupyterLab Droplet does not exist. Nothing to destroy!"
              exit 1
          else
              echo "JupyterLab Droplet exists. Good :-)"
          fi

          echo ::set-output name=droplet_id::$DO_ID

      - name: Destroy JupyterLab Droplet
        run: |
          doctl compute droplet delete ${{ steps.check_droplet.outputs.droplet_id }} --force