name: Build & Deploy
on: 
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check 22 port
        run: |
          nc -zvw10 ${{ steps.create_droplet.outputs.public_ip }} 22 

      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 104.248.169.162
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: root
     
          script: |
            ls
            echo 'Deployment successful to digital ocean' 